from selenium.webdriver.common.by import By



class Locators:

    SCOOTER_COOP_DAYS_HEADER = By.CLASS_NAME, "Home_Header__iJKdX"
    QUESTIONS_IMPORTANT = By.CLASS_NAME, "Home_SubHeader__zwi_E"
    COOKIE_ELEMENT = By.CLASS_NAME, "App_CookieButton__3cvqF"
    QUESTION_1 = By.ID, "accordion__heading-0"
    QUESTION_1_HEADER = By.XPATH, ".//div[@aria-labelledby= 'accordion__heading-0']/p"
    QUESTION_2 = By.ID, "accordion__heading-1"
    QUESTION_2_HEADER = By.XPATH, ".//div[@aria-labelledby= 'accordion__heading-1']/p"
    QUESTION_3 = By.ID, "accordion__heading-2"
    QUESTION_3_HEADER = By.XPATH, ".//div[@aria-labelledby= 'accordion__heading-2']/p"
    QUESTION_4 = By.ID, "accordion__heading-3"
    QUESTION_4_HEADER = By.XPATH, ".//div[@aria-labelledby= 'accordion__heading-3']/p"
    QUESTION_5 = By.ID, "accordion__heading-4"
    QUESTION_5_HEADER = By.XPATH, ".//div[@aria-labelledby= 'accordion__heading-4']/p"
    QUESTION_6 = By.ID, "accordion__heading-5"
    QUESTION_6_HEADER = By.XPATH, ".//div[@aria-labelledby= 'accordion__heading-5']/p"
    QUESTION_7 = By.ID, "accordion__heading-6"
    QUESTION_7_HEADER = By.XPATH, ".//div[@aria-labelledby= 'accordion__heading-6']/p"
    QUESTION_8 = By.ID, "accordion__heading-7"
    QUESTION_8_HEADER = By.XPATH, ".//div[@aria-labelledby= 'accordion__heading-7']/p"

    ORDER_BUTTON_1 = By.CLASS_NAME, "Button_Button__ra12g"
    FOR_WHOM_ELEMENT = By.CLASS_NAME, "Order_Header__BZXOb"
    NAME_INPUT = By.XPATH, ".//div[@class = 'Input_InputContainer__3NykH'][1]/input[@class = 'Input_Input__1iN_Z Input_Responsible__1jDKN']"
    NAME_ERROR = By.XPATH, ".//div[@class = 'Input_InputContainer__3NykH'][1]/div[@class = 'Input_ErrorMessage__3HvIb Input_Visible___syz6']"
    SURNAME_INPUT = By.XPATH, ".//div[@class = 'Input_InputContainer__3NykH'][2]/input[@class = 'Input_Input__1iN_Z Input_Responsible__1jDKN']"
    SURNAME_ERROR = By.XPATH, ".//div[@class = 'Input_InputContainer__3NykH'][2]/div[@class = 'Input_ErrorMessage__3HvIb Input_Visible___syz6']"
    ADDRESS_INPUT = By.XPATH, ".//div[@class = 'Input_InputContainer__3NykH'][3]/input[@class = 'Input_Input__1iN_Z Input_Responsible__1jDKN']"
    ADDRESS_ERROR = By.XPATH, ".//div[@class = 'Input_InputContainer__3NykH'][3]/div[@class = 'Input_ErrorMessage__3HvIb Input_Visible___syz6']"
    METRO_STATION_INPUT = By.CLASS_NAME, "select-search__input"
    METRO_STATION_UL_2 = By.XPATH, ".//div[@class = 'select-search__select']/ul[@class = 'select-search__options']/li"
    PHONE_INPUT = By.XPATH, ".//div[@class = 'Input_InputContainer__3NykH'][4]/input[@class = 'Input_Input__1iN_Z Input_Responsible__1jDKN']"
    EMPTY_FIELD = By.CLASS_NAME, "App_App__15LM-"
    PHONE_ERROR = By.XPATH, ".//div[@class = 'Input_InputContainer__3NykH'][4]/div[@class = 'Input_ErrorMessage__3HvIb Input_Visible___syz6']"
    FURTHER_BUTTON = By.CLASS_NAME, "Button_Button__ra12g Button_Middle__1CSJM"
    METRO_STATION_ERROR = By.XPATH, "div[@class = 'Order_UnderError__1VSDB']/div[@class = 'Order_MetroError__1BtZb']"

    ABOUT_RENT_HEADER = By.CLASS_NAME, "Order_Header__BZXOb"
    SELECT_DELIVERY_DATE = By.XPATH, ".//div[@class = 'Order_MixedDatePicker__3qiay']//input[@class = 'Input_Input__1iN_Z Input_Responsible__1jDKN']"
    DIV_BUTTONS = By.XPATH, ".//div[@class = 'react-datepicker__month']//div[@class = 'react-datepicker__week']/div"
    SELECT_PAST_DATE = By.XPATH, ".//div[@class = 'react-datepicker__tab-loop']//div[@class = 'react-datepicker__week'][1]/div[@class= 'react-datepicker__day react-datepicker__day--027 react-datepicker__day--outside-month']"
    SELECT_FUTURE_DATE = By.XPATH, ".//div[@class = 'react-datepicker__tab-loop']//div[@class = 'react-datepicker__week'][4]/div[@class= 'react-datepicker__day react-datepicker__day--020']"
    SELECT_RENTAL_PERIOD = By.CLASS_NAME, "Dropdown-placeholder"
    SELECT_RENTAL_PERIOD_2 = By.XPATH, ".//div[@class = 'Dropdown-root is-open']//div[@class = 'Dropdown-menu']/div"
    SCOOTER_COLORS = By.CLASS_NAME, "Checkbox_Input__14A2w"
    COMMENT_INPUT = By.CLASS_NAME, "Input_Input__1iN_Z Input_Responsible__1jDKN"
    ORDER_BUTTON_3 = By.CLASS_NAME, "Button_Button__ra12g Button_Middle__1CSJM"
    PLACE_ORDER_HEADER = By.CLASS_NAME, "Order_ModalHeader__3FDaJ"
    YES_BUTTON = By.CLASS_NAME, "Button_Button__ra12g Button_Middle__1CSJM"
    SEE_STATUS_BUTTON = By.CLASS_NAME, "Button_Button__ra12g Button_Middle__1CSJM"
    ORDER_STATUS_ERROR = By.CLASS_NAME, "Track_OrderDescription__1bRk8"

    SCOOTER_BUTTON = By.XPATH, ".//a[@class = 'Header_LogoScooter__3lsAR']"
    YANDEX_BUTTON = By.XPATH, ".//a[@class = 'Header_LogoYandex__3TSOI']"
    YANDEX_LOGIN_BUTTON = By.CLASS_NAME, "base-button__rootElement-12__base-button__m-2y__base-button__regular--M"

