from selenium.webdriver.common.by import By



class Locators():

    SCOOTER_COOP_DAYS_HEADER = By.CLASS_NAME, "Home_Header__iJKdX"
    QUESTIONS_IMPORTANT = By.XPATH, "/html/body/div[1]/div/div/div[5]/div[1]"   #".//div[@class = 'App_App__15LM-']/div[@class = 'Home_HomePage__ZXKIX']/div[@class = 'Home_FourPart__1uthg']/div[@class = 'Home_SubHeader__zwi_E"
    COOKIE_ELEMENT = By.CLASS_NAME, "App_CookieButton__3cvqF"
    QUESTION_1 = By.XPATH, ".//div[@id = 'accordion__heading-0']"             #".//div[@class = 'accordion__item'][1]/div[@classs = 'accordion__heading']/div[@class = 'accordion__button']"    #"accordion__heading-8"
    QUESTION_1_HEADER = By.XPATH, ".//div[@aria-labelledby= 'accordion__heading-0']/p"   #".//div[@class = 'accordion__panel-8']/p"
    QUESTION_2 = By.XPATH, ".//div[@id = 'accordion__heading-1']"
    QUESTION_2_HEADER = By.XPATH, ".//div[@aria-labelledby= 'accordion__heading-1']/p"
    QUESTION_3 = By.XPATH, ".//div[@id = 'accordion__heading-2']"
    QUESTION_3_HEADER = By.XPATH, ".//div[@aria-labelledby= 'accordion__heading-2']/p"
    QUESTION_4 = By.XPATH, ".//div[@id = 'accordion__heading-3']"
    QUESTION_4_HEADER = By.XPATH, ".//div[@aria-labelledby= 'accordion__heading-3']/p"
    QUESTION_5 = By.XPATH, ".//div[@id = 'accordion__heading-4']"
    QUESTION_5_HEADER = By.XPATH, ".//div[@aria-labelledby= 'accordion__heading-4']/p"
    QUESTION_6 = By.XPATH, ".//div[@id = 'accordion__heading-5']"
    QUESTION_6_HEADER = By.XPATH, ".//div[@aria-labelledby= 'accordion__heading-5']/p"
    QUESTION_7 = By.XPATH, ".//div[@id = 'accordion__heading-6']"
    QUESTION_7_HEADER = By.XPATH, ".//div[@aria-labelledby= 'accordion__heading-6']/p"
    QUESTION_8 = By.XPATH, ".//div[@id = 'accordion__heading-7']"
    QUESTION_8_HEADER = By.XPATH, ".//div[@aria-labelledby= 'accordion__heading-7']/p"
    ORDER_BUTTON_1 = By.CLASS_NAME, "Button_Button__ra12g"
    ORDER_BUTTON_2 = By.XPATH, "/html/body/div[1]/div/div/div[4]/div[2]/div[5]/button"
    FOR_WHOM_ELEMENT = By.CLASS_NAME, "Order_Header__BZXOb"
    NAME_INPUT = By.XPATH, "/html/body/div[1]/div/div[2]/div[2]/div[1]/input"
    NAME_ERROR = By.XPATH, "/html/body/div[1]/div/div[2]/div[2]/div[1]/div"
    SURNAME_INPUT = By.XPATH, "/html/body/div[1]/div/div[2]/div[2]/div[2]/input"
    SURNAME_ERROR = By.XPATH, "/html/body/div[1]/div/div[2]/div[2]/div[2]/div"
    ADDRESS_INPUT = By.XPATH, "/html/body/div[1]/div/div[2]/div[2]/div[3]/input"
    ADDRESS_ERROR = By.XPATH, "/html/body/div[1]/div/div[2]/div[2]/div[3]/div"
    METRO_STATION_INPUT = By.CLASS_NAME, "select-search__input"
    METRO_STATION_UL = By.XPATH, ".//div[@class = 'select-search__select']/ul[@class = 'select-search__options']"
    METRO_STATION_UL_2 = By.XPATH, ".//div[@class = 'select-search__select']/ul[@class = 'select-search__options']/li"
    PHONE_INPUT = By.XPATH, "/html/body/div[1]/div/div[2]/div[2]/div[5]/input"        #".//div[@class = 'Input_InputContainer__3NykH'][4]/input[@class = 'Input_Input__1iN_Z Input_Responsible__1jDKN']"    #"/html/body/div[1]/div/div[2]/div[2]/div[5]/input"
    EMPTY_FIELD = By.XPATH, "/html/body/div[1]/div"
    PHONE_ERROR = By.XPATH, "/html/body/div[1]/div/div[2]/div[2]/div[5]/div"
    FURTHER_BUTTON = By.XPATH, ".//div[@class = 'Order_NextButton__1_rCA']/button[@class = 'Button_Button__ra12g Button_Middle__1CSJM']"
    METRO_STATION_ERROR = By.XPATH, "/html/body/div[1]/div/div[2]/div[2]/div[4]/div[2]"
    ABOUT_RENT_HEADER = By.XPATH, "/html/body//div[@class = 'Order_Header__BZXOb']"
    SELECT_DELIVERY_DATE = By.XPATH, ".//div[@class = 'Order_MixedDatePicker__3qiay']//input[@class = 'Input_Input__1iN_Z Input_Responsible__1jDKN']"
    DIV_BUTTONS = By.XPATH, ".//div[@class = 'react-datepicker__month']//div[@class = 'react-datepicker__week']/div"
    SELECT_PAST_DATE = By.XPATH, "/html/body/div[1]/div/div[2]/div[2]/div[1]/div[2]/div[2]/div/div/div[2]/div[2]/div[1]/div[3]"
    SELECT_RENTAL_PERIOD = By.XPATH, ".//div[@class = 'Dropdown-root']//span[@class = 'Dropdown-arrow']"
    SELECT_RENTAL_PERIOD_2 = By.XPATH, ".//div[@class = 'Dropdown-root is-open']//div[@class = 'Dropdown-menu']/div"
    SCOOTER_COLORS = By.XPATH, ".//div[@class = 'Order_Checkboxes__3lWSI']//input"
    COMMENT_INPUT = By.XPATH, ".//div[@class = 'Input_InputContainer__3NykH']//input[@class = 'Input_Input__1iN_Z Input_Responsible__1jDKN']"
    ORDER_BUTTON_3 = By.XPATH, "/html/body/div[1]/div/div[2]/div[3]/button[2]"   #".//div[@class = 'Order_Buttons__1xGrp']/button[2]"
    PLACE_ORDER_HEADER = By.CLASS_NAME, "Order_ModalHeader__3FDaJ"
    YES_BUTTON = By.XPATH, ".//div[@class = 'Order_Modal__YZ-d3']//button[@class = 'Button_Button__ra12g Button_Middle__1CSJM']"
    SEE_STATUS_BUTTON = By.XPATH, ".//div[@class = 'Order_Modal__YZ-d3']//button[@class = 'Button_Button__ra12g Button_Middle__1CSJM']"
    CANCEL_ORDER_BUTTON = By.CLASS_NAME, "Button_Button__ra12g Button_Middle__1CSJM Button_Inverted__3IF-i"
    ORDER_STATUS_ERROR = By.CLASS_NAME, "Track_OrderDescription__1bRk8"
    SCOOTER_BUTTON = By.XPATH, ".//a[@class = 'Header_LogoScooter__3lsAR']"
    YANDEX_BUTTON = By.XPATH, ".//a[@class = 'Header_LogoYandex__3TSOI']"
    YANDEX_LOGIN_BUTTON = By.XPATH, "/html/body/div[2]/div[2]/header/div/div[2]/div[3]/div/button"
    ALL_INPUTS_CLEAR = "/html/body/div[1]/div/div[2]/div[2]//input"      #"/html/body/div[1]//input['Input_Input__1iN_Z Input_Responsible__1jDKN']"      #".//div[@class = 'Order_Form__17u6u/']div"    #"/html/body/div[1]/div/div[2]/div[2]//input"

